KEY_STATUS_ACTIVE = "active"
KEY_STATUS_DISABLED = "disabled"
KEY_STATUS_INVALID = "invalid"
VALID_KEY_STATUSES = {KEY_STATUS_ACTIVE, KEY_STATUS_DISABLED, KEY_STATUS_INVALID}

PROVIDER_TYPE_OPENAI = "openai"
PROVIDER_TYPE_ANTHROPIC = "anthropic"
PROVIDER_TYPE_MINIMAX = "minimax"
PROVIDER_TYPE_GEMINI = "gemini"
PROVIDER_TYPE_PROXY = "proxy"
PROVIDER_TYPE_CUSTOM = "custom"

VALID_PROVIDER_TYPES = {
    PROVIDER_TYPE_OPENAI,
    PROVIDER_TYPE_ANTHROPIC,
    PROVIDER_TYPE_MINIMAX,
    PROVIDER_TYPE_GEMINI,
    PROVIDER_TYPE_PROXY,
    PROVIDER_TYPE_CUSTOM,
}

PROVIDER_DEFAULT_BASE_URLS = {
    PROVIDER_TYPE_OPENAI: "https://api.openai.com/v1",
    PROVIDER_TYPE_ANTHROPIC: "https://api.anthropic.com",
    PROVIDER_TYPE_MINIMAX: "https://api.minimax.chat",
    PROVIDER_TYPE_GEMINI: "https://generativelanguage.googleapis.com/v1beta/openai",
}

ROUTE_POLICY_TYPE_FIXED = "fixed"
ROUTE_POLICY_TYPE_FALLBACK = "fallback"
ROUTE_POLICY_TYPE_WEIGHTED = "weighted"
ROUTE_POLICY_TYPE_COST_FIRST = "cost_first"

VALID_ROUTE_POLICY_TYPES = {
    ROUTE_POLICY_TYPE_FIXED,
    ROUTE_POLICY_TYPE_FALLBACK,
    ROUTE_POLICY_TYPE_WEIGHTED,
    ROUTE_POLICY_TYPE_COST_FIRST,
}
